name = "AdversarialRobustness"
uuid = "7a74dc10-e776-4f2a-9e36-b9ba9a8e9776"
authors = ["Rithik Appachi Senthilkumar"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
